### ISSUE TITLE
PTV2: (1a) Persistence of settings to the preset.

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-template-base#107]
Problem 1a: Persistence of settings to the preset.
Observed behavior: I change something in the settings, close the plugin and re-open it. Then the setting options are reseted to the old values.
Expected behavior: If I change something in the settings, this should be stored immediately in the preset.

**Comment by bisoladebiyi** [comment]
@matteobu I believe this issue is linked with the `resetData()` problem, yes? and issue #112 & #108 ?

**Comment by matteobu** [comment]
The #112 yes it is, the #107 and #108 I am not sure yet.
I think we can find a workaround storing the information in the `window.dtableSDK` object
