### ISSUE TITLE
PTV2: (languages) Lang in prod is not working (issues 1,2,7,8)

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-template-base#188]
1. The translation "intl" is not initialized correctly in production.
2. I don't think that we need the variable "lang" in the setting.local.js any longer. We should assume that 'en' is the default language and in the documentation we explain how to add other languages. In dev we have this language switch from matteo and in production, the language decision comes from the personal settings of the user.
3. Can you fix the warnings about circular dependencies? src/index.js -> src/components/LanguageDropDown/index.tsx -> src/index.js
4. In DEV: Closing the plugin raises an error in the browser console: "can't perform a react state update on an unmounted component.

**Comment by christophdb** [comment]
Thanks for the work @matteobu @bisoladebiyi!
Most issues are solved now. 

There are still two issues, I think both are connected:

1) User-Language is not supported at all by the plugin
In SeaTable the user can select different languages in his personal settings. If I currently select spanish, then the plugin shows again empty strings. In this case, the plugin should fall back to the English strings.

![image](https://github.com/seatable/seatable-plugin-template-base/assets/7803347/2df7cfe2-4e14-4a24-8785-7f5238bdcef8)

2) missing translation in one of the language files

Imagine that you have a translation in the /lang/en.ts but not in /lang/de.ts. In this case, the plugin also shows an empty string if you select "de" as language. This behaviour is in DEV and PROD.

The desired behaviour would be that if a single translation or the complete translation is missing, the english version should be used instead of showing an empty string. 

This is the current behaviour of all existing plugins like Gallery, Kanban, ... 
It would be great if we provide the same function.

**Comment by matteobu** [comment]
@christophdb for the 2. point we can add a "default" for every translation `intl.get('preset_add').d('${en.preset_add}')` , I have not found a fallback solution with this library.

**Comment by matteobu** [comment]
@christophdb for the 1. I added a check if the lang exists in the AVAILABLE_LOCALES before setting the language, if not then en is set

`Object.values(AVAILABLE_LOCALES).includes(window.dtable.lang)`

**Comment by christophdb** [comment]
I only had the time to test this shortly. Here is what I can see so far.
- In PROD the plugin is now always English, no matter of the selected language of the user.
- I don't like that approach with adding a default value all the time. with .d(`${en.table}`). 
- Also I don't like that you have to load a language in one of the files like you do by adding "import en from '../../locale/lang/en' to components/PluginSettings/index.tsx. 

Can you try to find a more convenient way to solve this? Here is what I would like to achieve. The developer should have the possibilitiy to decide if he wants to translate his plugin.

Option 1) No translation
- the developer ignores internationalization and directly uses normal text strings in his plugin. AVAILABLE_LOCALES is empty. There are no language files or empty language files. 
=> There is no translation offered/used in dev or prod. 

Option 2) Translated plugin
- the developer decides to offer different languages.
- the developer defines the translations in the lang/xx.ts files. 
- the developer defines the available languages in AVAILABLE_LOCALES
- the developer uses {intl.get('xxx')} everywhere in the plugin.

Everything else should work out of the box: 
- in dev there is a language selector, to switch between the languages if there are some defined.
- in prod, the selected language of the user should be used.
- if a single translation line or a complete translation is missing, English should be used as fallback.

**Comment by matteobu** [comment]
> In PROD the plugin is now always English, no matter of the selected language of the user.
> I don't like that approach with adding a default value all the time. with .d(${en.table}).
> Also I don't like that you have to load a language in one of the files like you do by adding "import en from '../../locale/lang/en' to components/PluginSettings/index.tsx.

The English Issue in PROD should be solved now.
If a single translation is missing I have only found this solution as fallback `.d(${en.table}).`
I get that you don't like the `import`, so we can avoid this `.d(${en.table}).` and use this `.d('default message').`


>Option 2) Translated plugin
the developer decides to offer different languages.
the developer defines the translations in the lang/xx.ts files.
the developer defines the available languages in AVAILABLE_LOCALES
the developer uses {intl.get('xxx')} everywhere in the plugin.

These are achieved, so I would continue with Option 2



ATM the only decision we have to make is:
_In case of a single translation missing, what do we do?_

1.  We can assume that if a dev defines the available languages in AVAILABLE_LOCALES, it should define all the necessary single translations. I would not expect a dev to miss some keys for a specific lang. He's the only one having to do with translation, if then there is a missing single translation he needs to add it.
2. Even if we assume that point 1 is always taken into consideration by the developer, we can still consider some options in case the developer does not act correctly or does not want to define all the individual translations for each language.
Possible Solutions:
    - We do nothing, so the dev should fall in the 1. case where he is aware that he needs to define all the single translations.
    - We instruct the developer to add a single translation directly in the code `.d('default message')` adding the instructions in the README file. 
    
    
 I assume that adding a `.d('default message')` has the same effort as adding the single translation in the proper file `../../locale/lang/xx`, but eventually it solves any kind of missing keys.

**Comment by matteobu** [comment]
@christophdb 
I made a few changes to reduce the changes the user/dev has to make in the `src/locale/index.ts` file.
If you check the new file you can see that we import all the `lang/xx.ts` files from the lang folder and we then export everything in the `AVAILABLE_LOCALES` obj.
In this case, the dev does not need to add the import fora specific language in the `src/locale/index.ts` but he only needs to create the `lang/xx.ts` file in the lang folder. 
I moreover added the `DEFAULT_LOCALE` const where we store the default lang value taken from the `setting.local.js`, so I also restored this value in the `setting.local.js`.
So also in this case we avoid the dev/user manipulating other files rather than the `setting.local.js` which is already supposed to do. 

What do you think?

**Comment by matteobu** [comment]
PS: translation files are commonly JSON files
