### ISSUE TITLE
PTV2: (Settings) 3, Make a console error in case of wrong settings.local.js info

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-template-base#189]
if a setting in settings.local.js is wrong (like wrong server url or wrong API token, the plugin can not init a connection to the base and there is an ugly warning like "uncaught runtime errors - reading 'loadFromServer'. Would it make sense to capture this error and show an error message?

**Comment by matteobu** [comment]
FYI  @christophdb  
I asked Daniel about this error and this is his reply

> I think you need to modify dtable-sdk to raise a corresponding exception and show the error in the front end. At the other hand, only developers will modify setting.local.js during development phase, I think it is not needed to show the error in the page.

**Comment by christophdb** [comment]
ok. forget this request.
