### ISSUE TITLE
PTV2: (production) "Add Preset" margin

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-template-base#193]
In prod there is a 14px of bottom margin 

![Image](https://github.com/seatable/seatable-plugin-template-base/assets/62759388/d5a28c65-8ac7-44cb-963e-1c2d69c9bf91)

**Comment by bisoladebiyi** [comment]
Here too, below preset name on the header

![Image](https://github.com/seatable/seatable-plugin-template-base/assets/69858244/3a48be61-93c4-45e4-a424-61a815168c8e)

**Comment by matteobu** [comment]
Both fixed [here](https://github.com/seatable/seatable-plugin-template-base/pull/197/commits/acc2159f62a0edd853aaceed31193b816ff7bb52) and [here](https://github.com/seatable/seatable-plugin-template-base/pull/197/commits/86b5e77b7eefb11c517895210ee32a451bc9276b)
