### ISSUE TITLE
PTV2: (Views and Settings) Fix Response and mobile view

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-template-base#23]
1 - fix mobile response 
~~2 - buttons should be clickable on mobile~~

**Comment by bisoladebiyi** [comment]
Hey @matteobu , can you shed more light on this issue? What buttons should not be clickable?

**Comment by matteobu** [comment]
I have to update the issue, I think the buttons (header's buttons) are now working.
But still, the mobile layout of plugin settings needs a check.

**Comment by matteobu** [comment]
For reference, this is the issue I am talking about in the mobile view 

https://github.com/seatable/seatable-plugin-template-base/assets/62759388/fc19a4ff-1b99-4b1c-a074-9075471ab0ad


https://github.com/seatable/seatable-plugin-template-base/assets/62759388/224e0de6-ee84-4d16-ae87-97a32c68f0c7
