### ISSUE TITLE
PTV2: Adding a check for Preset Name

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-template-base#46]
@bisoladebiyi @christophdb 
Should we incorporate a validation mechanism to check for the existence of a preset name before allowing the user to input it? This would mimic the current functionality employed when creating a new view, ensuring consistency across the user experience.

![Image](https://github.com/seatable/seatable-plugin-template-base/assets/62759388/0e0e5003-baaa-4456-a048-f3e9c0ac9ea0)

**Comment by bisoladebiyi** [comment]
Yup, its a necessity even. We can try and stick to the same design as well  :)

**Comment by matteobu** [comment]
Ok, @bisoladebiyi  please leave it to me :)

**Comment by matteobu** [comment]
I am also

- Refactoring the `Input` to a separate component for consistency;
- Handling `toggleNewPresetPopUp` and `onNewPresetSubmit` in one function

**Comment by matteobu** [comment]
Blocked until I will work on a behaviour that needs to be fixed.
For more info look into the PR comments.
