### ISSUE TITLE
PTV2: Table Name should have a limit

### ISSUE THREAD

**Issue by bisoladebiyi** [seatable/seatable-plugin-template-base#49]
Table names should have a limit. 
@christophdb  I don't know which repo should address this issue

![Image](https://github.com/seatable/seatable-plugin-template-base/assets/62759388/2af54ab1-604e-4844-9e62-c730c49772a4)
![Image](https://github.com/seatable/seatable-plugin-template-base/assets/62759388/679aad5a-3e43-449a-9dff-9724cb921d03)

**Comment by bisoladebiyi** [comment]
@matteobu I have a fix in mind but this would be in the base template since other plugins would be built upon it. (This fix is for dropdown)

**My suggestion:**
- We trim down the names of tables (and bases) but add ellipses at the end (e.g Table Overview Tab...). Limiting words might take away the freedom of users to use descriptive names for their tables.

A separate fix would have to be done for the issue in image 1 (in the appropriate repo). What do you think?

**Comment by matteobu** [comment]
@bisoladebiyi Yes, trimming the name it's a good idea and in case add the ... 
I would anyway put a rule on name length in the Base when creating a new table.
