### ISSUE TITLE
PTV2: (Preset) onSelectPreset called two times

### ISSUE THREAD

**Issue by matteobu** [seatable/seatable-plugin-template-base#88]
@bisoladebiyi  can you please have a look at it?

When duplicating the Preset, the function `onSelectPreset` gets called two times
Have a look at this repo https://github.com/seatable/seatable-plugin-template-base/tree/TB-086

https://github.com/seatable/seatable-plugin-template-base/assets/62759388/6b8f0651-e0a1-4c74-b8f0-55a9ff072380

**Comment by matteobu** [comment]
@bisoladebiyi  I think the issue is that this function `onClick={onClickPreset}` gets called whenever we click on the Dropdown `Rename`, `Duplicate` and `Delete`.
This function is then calling the `onSelectPreset(v?._id)` which causes to reset the `presetIdx`.

I left some `console.log` around.

Can you have a look please?

**Comment by bisoladebiyi** [comment]
On it
